# TCL File Generated by Component Editor 15.1
# Wed Mar 30 21:16:15 CEST 2016
# DO NOT MODIFY


# 
# Processor "Processor" v1.0
#  2016.03.30.21:16:15
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module Processor
# 
set_module_property DESCRIPTION ""
set_module_property NAME Processor
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Processor
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Project
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file ALU.vhd VHDL PATH ALU.vhd
add_fileset_file Control.vhd VHDL PATH Control.vhd
add_fileset_file DeMux.vhd VHDL PATH DeMux.vhd
add_fileset_file Debouncer.vhd VHDL PATH Debouncer.vhd
add_fileset_file Full_Adder_2_1.vhd VHDL PATH Full_Adder_2_1.vhd
add_fileset_file Full_Adder_Gen.vhd VHDL PATH Full_Adder_Gen.vhd
add_fileset_file Full_Sub_2_1.vhd VHDL PATH Full_Sub_2_1.vhd
add_fileset_file Full_Sub_Gen.vhd VHDL PATH Full_Sub_Gen.vhd
add_fileset_file MUX_Proc.vhd VHDL PATH MUX_Proc.vhd
add_fileset_file Memory.vhd VHDL PATH Memory.vhd
add_fileset_file Mux_ALU.vhd VHDL PATH Mux_ALU.vhd
add_fileset_file Proc.vhd VHDL PATH Proc.vhd
add_fileset_file Project.vhd VHDL PATH Project.vhd TOP_LEVEL_FILE
add_fileset_file Regist.vhd VHDL PATH Regist.vhd
add_fileset_file segment_nombre.vhd VHDL PATH segment_nombre.vhd
add_fileset_file segment_nombre_dec.vhd VHDL PATH segment_nombre_dec.vhd
add_fileset_file segment_nombre_hexa.vhd VHDL PATH segment_nombre_hexa.vhd
add_fileset_file segment_signe.vhd VHDL PATH segment_signe.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_source
# 
add_interface clock_source clock start
set_interface_property clock_source associatedDirectClock ""
set_interface_property clock_source clockRate 0
set_interface_property clock_source clockRateKnown false
set_interface_property clock_source ENABLED true
set_interface_property clock_source EXPORT_OF ""
set_interface_property clock_source PORT_NAME_MAP ""
set_interface_property clock_source CMSIS_SVD_VARIABLES ""
set_interface_property clock_source SVD_ADDRESS_GROUP ""


# 
# connection point reset_source
# 
add_interface reset_source reset start
set_interface_property reset_source associatedClock clock_source
set_interface_property reset_source associatedDirectReset ""
set_interface_property reset_source associatedResetSinks ""
set_interface_property reset_source synchronousEdges DEASSERT
set_interface_property reset_source ENABLED true
set_interface_property reset_source EXPORT_OF ""
set_interface_property reset_source PORT_NAME_MAP ""
set_interface_property reset_source CMSIS_SVD_VARIABLES ""
set_interface_property reset_source SVD_ADDRESS_GROUP ""


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_source
set_interface_property avalon_slave_0 associatedReset ""
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 SW writebyteenable_n Input 18
add_interface_port avalon_slave_0 LEDR readdata Output 18
add_interface_port avalon_slave_0 LEDG readdata Output 8
add_interface_port avalon_slave_0 KEY writebyteenable_n Input 4
add_interface_port avalon_slave_0 CLOCK_50 beginbursttransfer Input 1
add_interface_port avalon_slave_0 HEX0 readdata Output 7
add_interface_port avalon_slave_0 HEX1 readdata Output 7
add_interface_port avalon_slave_0 HEX2 readdata Output 7
add_interface_port avalon_slave_0 HEX3 readdata Output 7
add_interface_port avalon_slave_0 HEX4 readdata Output 7
add_interface_port avalon_slave_0 HEX5 readdata Output 7
add_interface_port avalon_slave_0 HEX7 readdata Output 7
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0

